import React from "react";

const cuisineColors = {
    Japanese: '#c9b1ff',
    Nepalese: '#ffcaf2',
    Malaysian: '#ffb2b1',
    Thai: '#fff3ad',
    "Puerto Rican": '#bcffbc',
    Indian: '#a2edff',
    Lebanese: '#c9b1ff',
    Cantonese: '#ffcaf2',
    Sichuan: '#b797ff',
    Bangladeshi: '#caffd7',
    "Chinese Noodles": '#ffcbcb',
    "Cocktail Bar": '#adb9ff',
    Diner: '#ffbcff',
    Dumplings: '#ffa2ed',
    Spanish: '#a67eff',
    French: '#f2caff',
    Greek: '#e7ffb1',
    Nigerian: '#b1c0ff',
    "Chinese (Vegan)": '#f0b1ff',
    Pizza: '#c0ffb1',
    Bakery: '#fff0b1',
    Italian: '#b1ffc9',
    Palestinian: '#ffc9b1',
    "Breakfast/Brunch": '#b1e7ff',
    Turkish: '#dbcbff',
    Burmese: '#ddb1ff',
    Vietnamese: '#ffcad8',
    Dessert: '#cafff2',
    Georgian: '#d8ffca',
    Jamaican: '#caf2ff',
    "Bubble Tea": '#f2ffca',
    "Japanese Tea": '#d7caff',
    "Indian Tea": '#ffcae5',
    "African Tea": '#b1feff',
    "Southern Food": '#ffb1d7',
    Seafood: '#ffd9b1',
    "Korean Barbecue": '#b1d7ff',
    Korean: '#b1ffd9',
    Taiwanese: '#b2b1ff',
    Trinidadian: '#b1ffb2',
    Bagels: '#ffb1fe',
    Tibetan: '#ffc6b1',
    Mexican: '#ffcaad',
    "Dim Sum": '#e2ffad',
    Colombian: '#caadff',
    "Beer Hall": '#ade2ff',
    German: '#f3adff',
    Pub: '#adfff3',
    "Wine Bar": '#ffadb9',
    Filipino: '#fff7c7',
    Shanghainese: '#f7ffad',
    Syrian: '#deffbc',
    Haitian: '#bcffde',
    Dominican: '#ffbcde',
    Henan: '#debcff',
    "Xi'an": '#ffbcbc',
    Poke: '#bcbcff'
}

export default cuisineColors